# question_data = [
#     {"text": "A slug's blood is green.", "answer": "True"},
#     {"text": "The loudest animal is the African Elephant.", "answer": "False"},
#     {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
#     {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
#     {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
#     {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
#     {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
#     {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
#     {"text": "Google was originally called 'Backrub'.", "answer": "True"},
#     {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
#     {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
#     {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
# ]

question_data = [{"type":"boolean","difficulty":"medium","category":"Science: Computers",
      "question":"Android versions are named in alphabetical order.","correct_answer":"True","incorrect_answers":["False"]},
     {"type":"boolean","difficulty":"medium","category":"Science: Computers",
      "question":"All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.","correct_answer":"False","incorrect_answers":["True"]},
     {"type":"boolean","difficulty":"medium","category":"Science: Computers",
      "question":"The last Windows operating system to be based on the Windows 9x kernel was Windows 98.","correct_answer":"False","incorrect_answers":["True"]},
     {"type":"boolean","difficulty":"medium","category":"Science: Computers",
      "question":"The open source program Redis is a relational database server.","correct_answer":"False","incorrect_answers":["True"]},
     {"type":"boolean","difficulty":"medium","category":"Science: Computers",
      "question":"The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard Mark II computer.","correct_answer":"True","incorrect_answers":["False"]},
     {"type":"boolean","difficulty":"medium","category":"Science: Computers",
      "question":"AMD created the first consumer 64-bit processor.","correct_answer":"True","incorrect_answers":["False"]},
     {"type":"boolean","difficulty":"medium","category":"Science: Computers",
      "question":"To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ","correct_answer":"True","incorrect_answers":["False"]},
     {"type":"boolean","difficulty":"medium","category":"Science: Computers",
      "question":"The HTML5 standard was published in 2014.","correct_answer":"True","incorrect_answers":["False"]},
     {"type":"boolean","difficulty":"medium","category":"Science: Computers",
      "question":"Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.","correct_answer":"False","incorrect_answers":["True"]},
     {"type":"boolean","difficulty":"medium","category":"Science: Computers",
      "question":"The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.","correct_answer":"False","incorrect_answers":["True"]}]
    